config/routes.rb
Chat::Application.routes.draw do
  devise_for :users
  
  match "lobby" => "lobby#index", via: [:get]

  match "chatroom/new" => "lobby#new", as: "new_chatroom", via: [:get]
  match "chatroom/create" => "lobby#create", as: "create_chatroom", via: [:post]
  match "chatroom/set" => "lobby#setroom", as: "set_chatroom", via: [:post]
  
  match "messages" => "messages#index", via: [:get]
  match "messages" => "messages#create", via: [:post]
  match "messages/invite" => "messages#invite", via: [:get,:post]

  root to: "lobby#index"
end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
  attr_accessible :identifier, :name, :private, :created_by, :shared_with
  validate :add_username_to_private_identifier, before: :create
  validate :ensure_no_whitespaces, before: :create
  has_many :chatroom_members
  has_many :users, through: :chatroom_members
  

  validates :name, presence: true
  validates :identifier, presence: true, uniqueness: true, length: { maximum: 50 }

  private
    def ensure_no_whitespaces
      self.identifier = self.identifier.gsub(/\W+/,"_")
    end
    def add_username_to_private_identifier
      if self.private
        self.identifier = self.identifier + User.find_by_id(self.created_by).username
      end
    end
end

app/models/chatroom_member.rb
class ChatroomMember < ActiveRecord::Base
  attr_accessible :chatroom_id, :user_id, :private
  belongs_to :user
  belongs_to :chatroom
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :username, :identifier
  validates :content, presence: true
  validates :username, presence: true
  validates :identifier, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  has_many :chatroom_members
  has_many :chatrooms, through: :chatroom_members
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lobby_controller.rb
class LobbyController < ApplicationController
  def index
    if user_signed_in?
      @public_chatrooms = Chatroom.where(private: false)
      @private_chatrooms = User.find(current_user.id).chatrooms.where(private: true)
    
      respond_to do |format|
        format.js
        format.html
      end
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @chatroom = Chatroom.new
    respond_to do |format|
      format.html
    end
  end

  def create
    @chatroom = Chatroom.new(params[:chatroom].merge(created_by: current_user.id))

    respond_to do |format|
      if @chatroom.save
        ChatroomMember.create!(user_id: current_user.id, chatroom_id: @chatroom.id, private: @chatroom.private)
        format.html { redirect_to lobby_path }
      else
        format.html { redirect_to lobby_path }
      end
    end
  end

  def setroom
    session[:chat_identifier] = params[:identifier]
    respond_to do |format|
      format.json { redirect_to messages_path }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @room = Chatroom.find_by_identifier(session[:chat_identifier])
    @messages = Message.find_all_by_identifier(session[:chat_identifier])
    @msg = Message.new #For the form partial.
    @private = @room.private?
    @owner = User.find_by_id(@room.created_by)
    @members = @room.users
        
    if session[:chat_identifier].nil?
      redirect_to lobby_path
    else
      respond_to do |format|
        format.html
        format.json { render json: @messages }
      end
    end
  end

  def create
    @message = Message.new(params[:message].merge(username: current_user.username, identifier: session[:chat_identifier]))
    respond_to do |format|
      if @message.save
        format.js
        format.html { redirect_to messages_path }
      else
        format.js
        format.html { redirect_to messages_path }
      end
    end
  end

  def invite
    @user = User.find_by_username(params[:invite])
    @room = Chatroom.find_by_identifier(session[:chat_identifier])
    @private = @room.private?
    @owner = User.find_by_id(@room.created_by)
    @members = @room.users
    if @user
      @member = ChatroomMember.new(user_id: @user.id, chatroom_id: @room.id, private: @private)
      respond_to do |format|
        if @member.save
          format.js
          format.html { render partial: '/messages/members', layout: false }
          format.json { redirect_to messages_path }
        else
          format.js
          format.html { render partial: '/messages/members', layout: false }
          format.json { redirect_to messages_path }
        end
      end      
    else
      respond_to do |format|
        format.js
        format.html { render partial: '/messages/members', layout: false }
        format.json { render nothing: true }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lobby_helper.rb
module LobbyHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Chat
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container-fluid
      = yield

app/views/lobby/index.html.haml
.row-fluid
  %h2 Lobby
  - if user_signed_in?
    Signed in as #{current_user.username}
    = link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    = link_to 'Sign in', new_user_session_path
    |
    = link_to 'Sign up', new_user_registration_path
  %br
  Session info: 
  %span#debug= session[:chat_identifier]
  %br
  %br
  .chatrooms
    - unless @public_chatrooms.empty?
      %b Public
      - @public_chatrooms.each do |chatroom|
        .chatroom{data: chatroom.identifier}
          = link_to chatroom.name, messages_path
    
    - unless @private_chatrooms.empty?
      %br
      %b Private
      - @private_chatrooms.each do |chatroom|
        .chatroom{data: chatroom.identifier}
          = link_to chatroom.name, messages_path

  %br       
  = link_to "New Chatroom", new_chatroom_path

app/views/lobby/new.html.haml
.row-fluid
  = simple_form_for @chatroom, url: url_for(action: "create", controller: "lobby") do |f|
    = f.input :name
    = f.input :identifier
    = f.input :private
    = f.button :submit

app/views/messages/_form.html.haml
= simple_form_for @msg, remote: true do |f|
  .content= f.input :content, label: false

app/views/messages/_members.html.haml
.member= "*"+@owner.username
- @members.each do |member|
  - unless member.id == @owner.id
    .member
      = member.username

app/views/messages/_messages.html.haml
- @messages.each do |msg|
  .message
    = msg.username + ": "
    = msg.content
    %br

app/views/messages/create.js.erb
<% publish_path = "/" + session[:chat_identifier] %>
<% publish_to publish_path do %>
  $(".messages").append('<div class="message"><%= escape_javascript @message.username %>: <%= escape_javascript @message.content %></div>');
  $(".messages").animate({ scrollTop: $('.messages')[0].scrollHeight}, 1000)
<% end %>
$('form#new_message')[0].reset();
$(".messages").animate({ scrollTop: $('.messages')[0].scrollHeight}, 1000)

app/views/messages/index.html.haml
.row-fluid
  %h2 Chat
  - if user_signed_in?
    Signed in as #{current_user.username}
    = link_to 'Sign out', destroy_user_session_path, method: :delete
    - if @room.private?
      #invite= link_to 'Add user to private chatroom', "#"
      #invitequery= text_field_tag 'inviteform', "", placeholder: "Enter username"

  - else
    = link_to 'Sign in', new_user_session_path
    |
    = link_to 'Sign up', new_user_registration_path
  %br

- if user_signed_in?
  Session info: 
  %span#debug= session[:chat_identifier]
  %br
  = link_to "Return to Lobby", lobby_path
  %br
  .messages.inline= render 'messages'
  - if @private
    .members.inline= render 'members'
  %br.clearBoth

  .row-fluid
    .chatform.inline= render 'form'
    - if current_user.id == @owner.id
      #editmember= link_to "Edit Member", "#"
      .editmembers.inline= select_tag "users", options_from_collection_for_select(@members, "id", "username"), include_blank: true
      #rmmember.inline= link_to "Remove Member", '#'
    %br.clearBoth

  = subscribe_to "/" + session[:chat_identifier]

app/views/messages/invite.js.erb
$('.members.inline').load('/messages/invite')